import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faNairaSign } from "@fortawesome/free-solid-svg-icons";
import { faFreeCodeCamp } from "@fortawesome/free-brands-svg-icons";
import Navbar from "../components/navbar";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Livestream</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* &#39 */}

      <div className={styles.heading}>
        <p className={styles.headingBox}>Premier League</p>
        <p className={styles.headingBox}>Regular Season</p>
      </div>
      <p className={styles.stJamesPark}>St. James&apos; Park</p>
      <div className={styles.scoreLine}>
        <div className={styles.scoreLineBox}>
          <p className={styles.scoreLineBoxItem}>Chelsea Logo</p>
          <p className={styles.scoreLineBoxItem}>Chelsea</p>
        </div>
        <div className={styles.scoreLineBox}>
          <p className={styles.scoreLineBoxItem}>1 : 0</p>
          <p className={styles.scoreLineBoxItem}>49 : 30</p>
        </div>
        <div className={styles.scoreLineBox}>
          <p className={styles.scoreLineBoxItem}>Leicester Logo</p>
          <p className={styles.scoreLineBoxItem}>Leicester</p>
        </div>
      </div>
      <div className={styles.gameCenterContainer}>
        <button className={styles.gameCenter}>GAME CENTER</button>
      </div>
      <div className={styles.mainBody}>
        <div className={styles.upperStatsContainer}>
          <div className={styles.upperStats}>
            <p className={styles.upperStatsText}>1</p>
            <p className={styles.upperStatsText}>1.95</p>
          </div>

          <div className={styles.upperStats}>
            <p className={styles.upperStatsText}>X</p>
            <p className={styles.upperStatsText}>3.66</p>
          </div>

          <div className={styles.upperStats}>
            <p className={styles.upperStatsText}>2</p>
            <p className={styles.upperStatsText}>4.34</p>
          </div>
        </div>
        <div className={styles.lowerStatsContainer}>
          <div className={styles.lowerStats}>
            <p>20%</p>
            <p>{"(4)"}</p>
          </div>
          <div className={styles.lowerStats}>
            <p>15%</p>
            <p>{"(3)"}</p>
          </div>
          <div className={styles.lowerStats}>
            <p>65%</p>
            <p>{"(13)"}</p>
          </div>
        </div>
        <hr />
        <div className={styles.stream}>
          <h2>LIVE STREAM</h2>
          <div className={styles.livePlayContainer}>
            <div className={styles.livePlay}>
              <button className={styles.play}></button>
              <h4>Chelsea - Manchester City</h4>
              <p>Livestream</p>
            </div>
            <p>
              Estoril and Santa Carla will play each other on Monday, November
              29th, 2021.
            </p>
          </div>
        </div>
      </div>

      <Navbar />
    </div>
  );
};

export default Home;
