import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Leagues.module.css"

export const Leagues = () => {
  return (
    <>
      <Head>
        <title>Leagues</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.headingBody}>
        <div className={styles.heading}>
          <h1>LEAGUES</h1>
          <p>Calendar</p>
        </div>
      </div>
  
      <div></div>
      <div></div>
      <div>
        <div>
          <div>Premier League Logo</div>
          <div>
            <h2>Premier League</h2>
            <div>
              <div>
                <p></p>
                <p>England</p>
              </div>
              <div>
                <p></p>
                <p>20 Teams</p>
              </div>
            </div>
          </div>
        </div>
        <div>
          <button>FOLLOW</button>
        </div>
        <div>
          <button>Overview</button>
          <button>Content</button>
          <button>Stats</button>
        </div>
      </div>
      <div>
        <h2>TOP PLAYERS</h2>
      </div>
      <div>
        <div>
          <select></select>
        </div>
        <div>
          <div>1</div>
          <div>
            <Image alt="" src="" />
            <Image alt="" src="" />
          </div>
          <div>
            <strong>Romelu Lukaku</strong>
            <br />
            <p>Defensive Midfielder</p>
          </div>
          <div>
            <button>8.03</button>
          </div>
        </div>
        <div>
          <div>2</div>
          <div>
            <Image alt="" src="" />
            <Image alt="" src="" />
          </div>
          <div>
            <strong>Goran Čaušić</strong>
            <br />
            <p>Central Midfielder</p>
          </div>
          <div>
            <button>7.90</button>
          </div>
        </div>
        <div>
          <div>3</div>
          <div>
            <Image alt="" src="" />
            <Image alt="" src="" />
          </div>
          <div>
            <strong>Francesco Caputo</strong>
            <br />
            <p>Attacking Midfielder</p>
          </div>
          <div>
            <button>7.90</button>
          </div>
        </div>
        <div>
          <div>4</div>
          <div>
            <Image alt="" src="" />
            <Image alt="" src="" />
          </div>
          <div>
            <strong>Randol Kolo Mauni</strong>
            <br />
            <p>Right Midfielder</p>
          </div>
          <div>
            <button>7.88</button>
          </div>
        </div>
        <div>
          <div>5</div>
          <div>
            <Image alt="" src="" />
            <Image alt="" src="" />
          </div>
          <div>
            <strong>Robin Pröpper</strong>
            <br />
            <p>Defensive Midfielder</p>
          </div>
          <div>
            <button>7.87</button>
          </div>
        </div>
        <div>
          <div>6</div>
          <div>
            <Image alt="" src="" />
            <Image alt="" src="" />
          </div>
          <div>
            <strong>Axel Witsel</strong>
            <br />
            <p>Defensive Winger</p>
          </div>
          <div>
            <button>7.65</button>
          </div>
        </div>
        <div>
          <div>7</div>
          <div>
            <Image alt="" src="" />
            <Image alt="" src="" />
          </div>
          <div>
            <strong>Phillip Lahm</strong>
            <br />
            <p>Right Winger</p>
          </div>
          <div>
            <button>7.65</button>
          </div>
        </div>
        <div>
          <div>8</div>
          <div>
            <Image alt="" src="" />
            <Image alt="" src="" />
          </div>
          <div>
            <strong>Gerd Müller</strong>
            <br />
            <p>Goalkeeper</p>
          </div>
          <div>
            <button>7.62</button>
          </div>
        </div>
        <div>
          <div>9</div>
          <div>
            <Image alt="" src="" />
            <Image alt="" src="" />
          </div>
          <div>
            <strong>Mikel Arteta</strong>
            <br />
            <p>Striker</p>
          </div>
          <div>
            <button>7.44</button>
          </div>
        </div>
        <div>
          <div>10</div>
          <div>
            <Image alt="" src="" />
            <Image alt="" src="" />
          </div>
          <div>
            <strong>Virgl Casémiro</strong>
            <br />
            <p>Left Winger</p>
          </div>
          <div>
            <button>7.37</button>
          </div>
        </div>
      </div>
    </>
  );
};
